{% set version = "22.1.0" %}
{% set major = version.split(".")[0] %}

package:
  name: flang-rt-split
  version: {{ version }}

source:
  url: https://github.com/llvm/llvm-project/archive/refs/tags/llvmorg-{{ version.replace(".rc", "-rc") }}.tar.gz
  sha256: 933765a1c2cd518d95a9033a92d88d7109a79aefa4609247c31f28b8bc8dd96e

build:
  number: 0
  # intentionally only windows (main target) & linux (debuggability)
  skip: true  # [osx]

requirements:
  build:
    - cmake
    - ninja
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - flang =={{ version }}
    # only to avoid pulling in newer rc's which have a different SONAME
    - libllvm{{ major }} =={{ version }}
  host:
    - clangdev =={{ version }}
    - compiler-rt =={{ version }}
    - llvmdev =={{ version }}
    - mlir =={{ version }}

outputs:
  - name: libflang-rt
    build:
      # not supported on windows yet, see
      # https://github.com/llvm/llvm-project/issues/134186
      skip: true  # [win]
    files:
      - lib/libflang_rt.runtime.so  # [linux]
    requirements:
      build:
        # for strong run-exports
        - {{ stdlib('c') }}
      run_constrained:
        # avoid old flang runtime
        - libflang <0.0a0
    test:
      commands:
        # shared library; copied from target-specific location
        - test -f $PREFIX/lib/libflang_rt.runtime.so    # [linux]

  - name: flang-rt_{{ target_platform }}
    build:
      noarch: generic
    files:
      - lib/clang/{{ major }}/lib/x86_64-unknown-linux-gnu/libflang_rt.runtime.a                # [linux]
      - lib/clang/{{ major }}/lib/x86_64-unknown-linux-gnu/libflang_rt.runtime.so               # [linux]
      # corresponding to different flavours of the MSVC runtime, i.e. `/MD`, `/MDd`, `/MT`, `/MTd`
      - Library/lib/clang/{{ major }}/lib/x86_64-pc-windows-msvc/flang_rt.runtime.static.lib    # [win]
      - Library/lib/clang/{{ major }}/lib/x86_64-pc-windows-msvc/flang_rt.runtime.dynamic.lib   # [win]
      - Library/lib/clang/{{ major }}/lib/x86_64-pc-windows-msvc/flang_rt.runtime.static_dbg.lib    # [win]
      - Library/lib/clang/{{ major }}/lib/x86_64-pc-windows-msvc/flang_rt.runtime.dynamic_dbg.lib   # [win]
    requirements:
      build:
        # for strong run-exports
        - {{ stdlib('c') }}     # [linux]
      host:
        - clangdev =={{ version }}
        - compiler-rt =={{ version }}
        - llvmdev =={{ version }}
        - mlir =={{ version }}
      run:
        - clangdev =={{ version }}
        - flang =={{ version }}
    test:
      commands:
        # target-specific runtime library location (default for flang)
        - test -f $PREFIX/lib/clang/{{ major }}/lib/x86_64-unknown-linux-gnu/libflang_rt.runtime.a                      # [linux]
        - test -f $PREFIX/lib/clang/{{ major }}/lib/x86_64-unknown-linux-gnu/libflang_rt.runtime.so                     # [linux]
        - if not exist %LIBRARY_LIB%\clang\{{ major }}\lib\x86_64-pc-windows-msvc\flang_rt.runtime.static.lib exit 1    # [win]
        - if not exist %LIBRARY_LIB%\clang\{{ major }}\lib\x86_64-pc-windows-msvc\flang_rt.runtime.dynamic.lib exit 1   # [win]
        - if not exist %LIBRARY_LIB%\clang\{{ major }}\lib\x86_64-pc-windows-msvc\flang_rt.runtime.static_dbg.lib exit 1    # [win]
        - if not exist %LIBRARY_LIB%\clang\{{ major }}\lib\x86_64-pc-windows-msvc\flang_rt.runtime.dynamic_dbg.lib exit 1   # [win]

about:
  home: https://flang.llvm.org
  license: Apache-2.0
  license_file: flang/LICENSE.TXT
  summary: Flang is a Fortran compiler targeting LLVM.
  dev_url: https://github.com/llvm/llvm-project

extra:
  recipe-maintainers:
    - conda-forge/flang
    - h-vetinari
  feedstock-name: flang-rt
