azure:
  settings_win:
    variables:
      CONDA_BLD_PATH: C:\\bld\\
      MINIFORGE_HOME: C:\Miniforge
github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  error_overlinking: true
conda_forge_output_validation: true
# necessary to build flang-rt_<target> on windows, as it's the only output, and noarch
noarch_platforms:
  - linux_64
  - win_64
